### ISSUE TITLE
it is a nightmare to setup roda dev environment with crossing ~20+ classes/modules and some custom roda/sequel plugins with unreloader

### ISSUE THREAD

**Issue by okliv** [jeremyevans/rack-unreloader#10]
using `require` without reloading i set up in 2-5 minutes.

but when i decided to give to unreloader another chance, i've spent almost a day to make it work. and no luck.
it is a scream of the soul: i bagging you to do something with flawless roda reloading during development like in `rails`. it is very hard to solve specific reload issues in situation while simple `require` just works.  because i want to solve business issues not framework ones. i understand, i might not fully understand how require/unreloader works, but any of README instructions weren't helpful. it fits for some abstract spheric horse in vacuum, not real cases.

you can close or delete this issue, sorry, and thank you.

**Comment by jeremyevans** [comment]
@okliv I can understand your frustration, setting up reloading using `rack-unreloader` is definitely more challenging than when using Rails, which has reloading is built in.  I think the good news is you can use the reloader that Rails now uses (Zeitwerk) without any dependency on Rails, and setup is supposed to be fairly easy (https://github.com/fxn/zeitwerk#synopsis).  Have you tried using that? I noticed it isn't listed in Roda's README.  I apologize for that and will try to update the README to reflect that.

Personally, I don't have experience with Zeitwerk because one of the features I tend to rely on in my Roda applications is classes that are split into multiple files (such as route files that all reopen the same class to add routes), and I don't think Zeitwerk supports that or plans to.

As an example of how `rack-unreloader` can be used with Roda/Sequel, you can look at https://github.com/jeremyevans/roda-sequel-stack.  This gives an example of working reloading out of the box.

I think `rack-unreloader` can handle real cases. At least I do not consider all of my applications to be abstract spheric horses in vacuums.  However, by it's design choice to not override core methods, it will always be more work to set up reloading using `rack-unreloader`, compared to reloading solutions that do override core methods.

**Comment by andriytyurnikov** [comment]
Adding 2 cents here:
`graphql-ruby` relies heavily on eager loading of dependencies (coz of circular references all over the place). 

`sequel` sidesteps simple issue by using string/symbols instead of classes 
```ruby
many_to_one :artist, class: "App1::AlbumArtist"
```
And sure, same trick may be used with `graphql-ruby`.
```ruby
field :blog, 'Types::BlogType'
```

Sure, one may argue that authoring libraries with circular references is ... suboptimal to begin with, and one should carefully construct his dependency tree. 

Well, maybe, maybe not. 

Maybe being able to eager-require whole directories is a powerful enabler.
