### ISSUE TITLE
Using Unreloader breaks sessions plugin

### ISSUE THREAD

**Issue by edzhelyov** [jeremyevans/rack-unreloader#7]
I'm just starting with Roda and hit an issue that I'm unable to resolve:
```
class App < Roda
  plugin :all_verbs
  plugin :sessions, secret: '---'

  route do |r|
    r.on do
      'hello'
    end
  end
end
```
```
require 'rack/unreloader'
Reloader = Rack::Unreloader.new { App }

require 'roda'
require 'json'

Reloader.require 'app.rb'

run Reloader
```

When started it works correctly, but at the moment you add `session` call to the app.rb file it will break with `You're missing a session handler, try using the sessions plugin.`

For some reason the @env['rack.session'] is lost during the reloading.

**Comment by jeremyevans** [comment]
The problem here is that you didn't specify what classes to reload when reloading `app.rb`.  This causes rack-unreloader to use ObjectSpace to determine what classes the file added, which turns out to be:

OpenSSL::OCSP::CertificateId OpenSSL::OCSP::SingleResponse OpenSSL::OCSP::BasicResponse OpenSSL::OCSP::Response OpenSSL::OCSP::Request OpenSSL::OCSP::OCSPError OpenSSL::OCSP OpenSSL::PKCS5 Zlib::VersionError Zlib::BufError Zlib::MemError Zlib::StreamError Zlib::DataError Zlib::NeedDict Zlib::StreamEnd Zlib::Error Zlib OpenSSL::Config OpenSSL::ConfigError OpenSSL::Cipher::CipherError OpenSSL::Cipher OpenSSL::Buffering OpenSSL::X509::Name::RFC2253DN Roda::RodaPlugins::Sessions::RequestMethods Roda::RodaPlugins::Sessions::InstanceMethods Roda::RodaPlugins::Sessions::CookieTooLarge Roda::RodaPlugins::Sessions Roda::RodaPlugins::AllVerbs::RequestMethods Roda::RodaPlugins::AllVerbs OpenSSL::X509::Store OpenSSL::X509::StoreError OpenSSL::X509::StoreContext OpenSSL::X509::Revoked OpenSSL::X509::RevokedError OpenSSL::X509::Request OpenSSL::X509::RequestError OpenSSL::X509::Name OpenSSL::X509::NameError OpenSSL::X509::Extension OpenSSL::X509::ExtensionFactory OpenSSL::X509::ExtensionError OpenSSL::X509::CRL OpenSSL::X509::CRLError OpenSSL::X509::Certificate OpenSSL::X509::CertificateError IPAddr::InvalidPrefixError IPAddr::AddressFamilyError IPAddr::InvalidAddressError IPAddr::Error IPAddr Zlib::ZStream OpenSSL::PKey::DH OpenSSL::PKey::DHError OpenSSL::PKey::DSA OpenSSL::PKey::DSAError OpenSSL::PKey::RSA OpenSSL::PKey::RSAError OpenSSL::PKey::PKey OpenSSL::PKey::PKeyError OpenSSL::PKey OpenSSL::PKCS7::RecipientInfo OpenSSL::PKCS7::SignerInfo OpenSSL::PKCS7::PKCS7Error OpenSSL::PKCS7 OpenSSL::PKCS12::PKCS12Error OpenSSL::PKCS12 OpenSSL::Netscape::SPKI SecureRandom OpenSSL::SSL::SSLServer OpenSSL::SSL::SocketForwarder Roda::RodaPlugins::ErrorHandler::InstanceMethods Roda::RodaPlugins::ErrorHandler::ClassMethods Roda::RodaPlugins::ErrorHandler Base64 OpenSSL::X509::AttributeError OpenSSL::X509 OpenSSL::X509::Attribute OpenSSL::SSL::SSLSocket OpenSSL::ASN1::PrintableString OpenSSL::ASN1::NumericString OpenSSL::ASN1::UTF8String OpenSSL::ASN1::OctetString OpenSSL::ASN1::BitString OpenSSL::ASN1::Enumerated OpenSSL::ASN1::Integer OpenSSL::ASN1::Boolean OpenSSL::ASN1::Constructive OpenSSL::ASN1::Primitive OpenSSL::ASN1::T61String OpenSSL::ASN1::ASN1Data OpenSSL::ASN1::ASN1Error OpenSSL::ASN1 OpenSSL::ASN1::VideotexString OpenSSL::Engine::EngineError OpenSSL::Engine OpenSSL::Digest::Digest OpenSSL::Digest::SHA512 OpenSSL::Digest::SHA384 OpenSSL::Digest::SHA256 OpenSSL::Digest::SHA224 OpenSSL::Digest::SHA1 OpenSSL::Digest::RIPEMD160 OpenSSL::Digest::MDC2 OpenSSL::Digest::MD5 OpenSSL::Digest::MD4 OpenSSL::Digest::MD2 Zlib::GzipReader Zlib::GzipWriter Zlib::GzipFile::LengthError Zlib::GzipFile::CRCError Zlib::GzipFile::NoFooter Zlib::GzipFile::Error Zlib::GzipFile Zlib::Inflate Zlib::Deflate App::RodaResponse App::RodaRequest App OpenSSL::SSL::SSLContext OpenSSL::SSL::Session::SessionError OpenSSL::SSL::Session OpenSSL::SSL::SSLErrorWaitWritable OpenSSL::SSL::SSLErrorWaitReadable OpenSSL::SSL::SSLError OpenSSL::ExtConfig OpenSSL::SSL OpenSSL::Random::RandomError OpenSSL::Random OpenSSL::PKey::EC::Point::Error OpenSSL::PKey::EC::Group::Error OpenSSL::PKey::EC::Point OpenSSL::PKey::EC::Group OpenSSL::PKey::EC OpenSSL::PKey::ECError OpenSSL::Cipher::Cipher OpenSSL::Cipher::AES256 OpenSSL::Cipher::AES192 OpenSSL::Cipher::AES128 OpenSSL::Cipher::RC5 OpenSSL::Cipher::RC4 OpenSSL::Cipher::RC2 OpenSSL::Cipher::IDEA OpenSSL::Cipher::DES OpenSSL::Cipher::BF OpenSSL::Cipher::CAST5 OpenSSL::Cipher::AES OpenSSL::BNError OpenSSL::OpenSSLError OpenSSL::BN OpenSSL OpenSSL::HMAC OpenSSL::HMACError OpenSSL::Digest::DigestError OpenSSL::Digest Digest::Base Digest::Class Digest::Instance Digest OpenSSL::Netscape OpenSSL::Netscape::SPKIError OpenSSL::KDF::KDFError OpenSSL::KDF OpenSSL::ASN1::EndOfContent OpenSSL::ASN1::Set OpenSSL::ASN1::Sequence OpenSSL::ASN1::GeneralizedTime OpenSSL::ASN1::UTCTime OpenSSL::ASN1::ObjectId OpenSSL::ASN1::Null OpenSSL::ASN1::BMPString OpenSSL::ASN1::UniversalString OpenSSL::ASN1::GeneralString OpenSSL::ASN1::ISO64String OpenSSL::ASN1::GraphicString OpenSSL::ASN1::IA5String

That's obviously more classes then you want to reload.

You can fix this by adding a block to your `Reloader.require` call:

```ruby
Reloader.require('app.rb'){:App}
```

To troubleshoot issues like this, it's best to add a logger:

```ruby
require 'logger'
Reloader = Rack::Unreloader.new(:logger=>Logger.new($stdout)) { App }
```
