### ISSUE TITLE
REXML::Functions defines #name which breaks Reloader#all_classes

### ISSUE THREAD

**Issue by kranzky** [jeremyevans/rack-unreloader#9]
This can be fixed by changing [#L416](https://github.com/jeremyevans/rack-unreloader/blob/master/lib/rack/unreloader/reloader.rb#L416) to this:

```
if !mod.to_s.empty? && monitored_module?(mod)
```

**Comment by jeremyevans** [comment]
That would just break if a module overrides #to_s instead of #name, though I suppose overriding #to_s to return non-String is less likely.  Technically, overriding Module#name to return non-string breaks compatibility, and it should be REXML that should be fixed.  Maybe we should use: `!mod.name.to_s.empty?`?

**Comment by jeremyevans** [comment]
Looks like `REXML::Functions.name` actually raises, so `mod.name.to_s` won't work.  `mod.name rescue next` should be OK.
